version: '3.1'

services:
  db:
    image: postgres
    restart: always
    networks:
      - dash-net
    volumes:
      - postgres-database:/data
    env_file:
      - db-configs.env
    ports:
      - 5432:5422

  adminer:
    image: adminer
    restart: always
    networks:
      - dash-net
    ports:
      - 8082:8080

networks:
  dash-net:
    external: true

volumes:
  postgres-database:
    external: true