version: '3.1'

services:
  db:
    image: postgres
    restart: always
    networks:
      - dash-net
    volumes:
      - postgres-database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - db-configs.env
    expose:
      - "5432"

  adminer:
    image: adminer
    restart: always
    networks:
      - dash-net
    labels:
      - "traefik.docker.network=dash-net"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:dash-adminer.maristdash.tk"
      - "traefik.basic.port=8080"
    ports:
      - "8082:8080"

networks:
  dash-net:
    external: true
volumes:
  postgres-database:
    external: true
